export const TERMINAL_REDUCER_NAME = '@terminalReducer';
export const TERMINAL_SAGA_NAME = '@terminalSaga';

// Used reducer actions
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const RESET_INPUT_VALUE = 'RESET_INPUT_VALUE';
export const ADD_TERMINAL_ROW = 'ADD_TERMINAL_ROW';
export const CLEAR_TERMINAL = 'CLEAR_TERMINAL';
export const ADD_TERMINAL_HISTORY_ITEM = 'ADD_TERMINAL_HISTORY_ITEM';
export const SET_TERMINAL_HISTORY = 'SET_TERMINAL_HISTORY';
export const SET_HISTORY_INDEX = 'SET_HISTORY_INDEX';

// Used sagas actions
export const INCREASE_HISTORY_INDEX = 'INCREASE_HISTORY_INDEX';
export const DECREASE_HISTORY_INDEX = 'DECREASE_HISTORY_INDEX';
