export const SET_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const RESET_INPUT_VALUE = 'RESET_INPUT_VALUE';

export const ADD_TERMINAL_ROW = 'ADD_TERMINAL_ROW';
export const CLEAR_TERMINAL = 'CLEAR_TERMINAL';
