export const SET_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const RESET_INPUT_VALUE = 'RESET_INPUT_VALUE';

export const ADD_TERMINAL_ROW = 'ADD_TERMINAL_ROW';
export const CLEAR_TERMINAL = 'CLEAR_TERMINAL';

export const SET_TERMINAL_HISTORY = 'SET_TERMINAL_HISTORY';
export const ADD_TERMINAL_HISTORY = 'ADD_TERMINAL_HISTORY';

export const INCREASE_HISTORY_INDEX = 'INCREASE_HISTORY_INDEX';
export const DECREASE_HISTORY_INDEX = 'DECREASE_HISTORY_INDEX';
